### PR TITLE
Improvements for usability

### PR DESCRIPTION
**Pull request by npanuhin**
Hello @wooneusean! Cool project, I will follow its development. I've jotted down a couple of tweaks to improve usability and added minor style fixes - do you accept pull requests?

Among changes:
- `complete.json` is of no use in the repository, as it contains only your achievements
- Added scripts (`run.cmd` and `run.sh`) for those who don't know what Python is and how to install its packages)
- Added `python-Levenshtein` package, as suggested by `fuzzywuzzy` for improving speed
- You [forgot to close an open file](https://github.com/wooneusean/genshin-achievement-reader/pull/1/files#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1L11-R12) at the beginning of `main.py`

### CODE REVIEW

**Comment by wooneusean** [comment]
Hi @npanuhin, thanks for cleaning up the code and making those changes. I did this project on a whim with my spare time so its quite messy 😅.

**Comment by wooneusean** [comment]
By the way @npanuhin, you got any ideas on how to detect the tier of achievements? I was thinking of using template matching to find each achievement box, then comparing the tier icon, also using template matching. I'm fairly new to computer vision and stuff like this so the way I thought of is probably not the best.

**Comment by npanuhin** [comment]
*Hello! Sorry it took me so long to reply, I've been a bit busy*

## First, regarding your question:
Your idea was to use template matching and image recognition. Unfortunately, I can’t say anything about this, because I have never done such things before. This seems to be the only possible solution other than the one I want to talk about next:

I did a [similar project](https://github.com/npanuhin/Among-Us) a couple years ago, where my script automatically "detected objects" on player's screen and played Among Us. Here's how my technique worked, applying it to Genshin's achievements:

Suppose we take a screenshot of the entire screen and calculate its width and height (this is important because we will be relying on the distance in pixels from the screen borders). Here is an example (Full HD size, 1920x1080):

Pay close attention to the red line:


Let's zoom a bit:


**We can go along the red line and where the pixels change - this is the upper/lower border of the achievement box!**

Using the predefined position constants of such lines, we can cut out the achievement tier icon. We can then use your template matching algorithm to determine how many ✦ it has.

This approach can also help you in image-to-text recognition as it cuts out perfect achievement boxes which you can then feed into `pytesseract` for OCR.

The downside: we need to predefine the pixel positions of the lines, so the screenshot needs to be exactly 1910x1080. Or we can predetermine the width ratio, for example, the line should start at 200 pixels from the left border of an image that is 1920 wide. If we have an image that is 720 wide, we can calculate that the line should start at the 75th pixel (200 / 1920 * 720).
*This is probably too complicated, but I just wanted to share my ideas)*

## Secondly, I have a few proposals for improving the project:
1) It's too tedious to scroll through 300-400+ achievements - we can automate this using python to scroll the window (control the mouse)
2) The user has to do a lot of manual work each time they want to update their achievements: open the `complete.json` file, copy its contents, paste it into `update_script.js` at the correct line, copy the contents of `update_script.js` - all this can be done simply using python: paste the content where it should be and copy the result to the clipboard. The user is then left to open browser's devtools, paste the contents of the clipboard and press Enter. Maybe it can be simplified even further)

> Like I said, I don't have time right now to contribute to the project, but maybe I will in a couple of weeks)

**Comment by wooneusean** [comment]
@npanuhin thanks for the insights! Your knowledge really provides a lot of information and things to consider.
It is true what you say, pre-defining the window size for the placement of the red line is kinda fidgety.

> If we have an image that is 720 wide, we can calculate that the line should start at the 75th pixel (200 / 1920 * 720).

I feel that it is possible to do what you suggested too. My worry is just about how accurately can it determine whether or not that its a valid box. I will try it out though, and see what I can come up with.

> It's too tedious to scroll through 300-400+ achievements - we can automate this using python to scroll the window (control the mouse)

I agree as well, but the thing about auto scrolling is how will the program know when to stop? Or will the user be the one that stops it manually?

> The user has to do a lot of manual work each time they want to update their achievements: open the complete.json file, copy its contents, paste it into update_script.js at the correct line, cop....

This is definitely possible, will implement this when I get started back on this project.

> Like I said, I don't have time right now to contribute to the project, but maybe I will in a couple of weeks)

Its ok! This is project is just a hobby project, don't worry.

**Comment by npanuhin** [comment]
> I feel that it is possible to do what you suggested too. My worry is just about how accurately can it determine whether or not that its a valid box. I will try it out though, and see what I can come up with.

Yes, that's what I was worried about as well. Probably we can draw a better line ¯\\_(ツ)_/¯. I'll think about it more

> I agree as well, but the thing about auto scrolling is how will the program know when to stop? Or will the user be the one that stops it manually?

Consider the algorithm: take a screenshot, recognize everything and write it to the storage -> scroll the list by a little less than 1 screen -> recognize again -> scroll again -> etc... In this case, if the recognition did not add a single new achievement to the storage, then there are no more achievements left, so we scrolled through the whole list to the end and we can stop

**Pull request merged**
